"""Add cost column to Cars

Revision ID: ee2f803682e3
Revises: 095de81dc3be
Create Date: 2025-05-11 10:29:18.847152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee2f803682e3'
down_revision: Union[str, None] = '095de81dc3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('new_cost', sa.Float(), nullable=True))
    op.add_column('cars', sa.Column('old_cost', sa.Float(), nullable=True))
    op.drop_column('cars', 'cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('cost', sa.FLOAT(), nullable=True))
    op.drop_column('cars', 'old_cost')
    op.drop_column('cars', 'new_cost')
    # ### end Alembic commands ###
